/*
 *  ASTI Services (c) © 2010
 *  Consultoria de Software.
 */
/*
 * JCompanyPanel.java
 *
 * Created on 7/05/2010, 02:06:03 PM
 */
package org.sample.view;


import org.sample.beans.AbstractManageableIFrame;
import org.sample.beans.Filtro;
import org.sample.main.Principal;
import org.sample.dao.DepartamentoDAO;
import org.sample.pojo.Departamento;
import org.sample.beans.DataServiceException;
//import com.astiservices.base.data.Filtro;
//import com.astiservices.base.ui.AbstractMDI;
//import com.astiservices.sifae.app.DataServiceException;
//import com.astiservices.sifae.app.Formats;
//import com.astiservices.sifae.beans.Impuestos;
//import com.astiservices.components.MessageDialog;
//import com.astiservices.sifae.service.IInfoService;
//import com.astiservices.sifae.service.IProductService;
//import com.astiservices.sifae.service.SIFAEServices;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JPanel;
import org.developercircle.beans.JEditionDataProvider;
import org.developercircle.beans.JEditionListener;
import org.developercircle.beans.RichColumnModel;
import org.developercircle.beans.RichDataColumn;
import org.developercircle.beans.RichTableModel;

public class DepartamentoPanel extends JPanel implements JEditionDataProvider<Departamento>, JEditionListener<Departamento>, ListSelectionListener {

    private final String LIST_PANEL = "LISTING";
    private final String EDIT_PANEL = "EDITION";//tambien sera utilizado como bandera para hacer save or update
    private AbstractManageableIFrame janf;
    private Principal app;
    private RichTableModel model;
    private Departamento departamentoToEdit;
    private DepartamentoDAO daoDepartamento;
    private String currentView;
    private boolean  isEdit=false;

    public DepartamentoPanel(AbstractManageableIFrame janf, Principal app) {
        initComponents();
        this.janf = janf;
        this.app = app;
        daoDepartamento=new DepartamentoDAO();
        initOtherComponent();
    }
    private void initOtherComponent() {
        showOnLayout(LIST_PANEL);
        fillComboSearch();
        createTableDepartamento();
        jtableProducts.getSelectionModel().addListSelectionListener(this);
        jeditionBar.setDataProvider(this);
        jeditionBar.setEditionListener(this);
        jeditionBar.active();
        doEnableBar();
    }
    //@Override
    public void activate() {
            showOnLayout(LIST_PANEL);
            refreshData();
            departamentoToEdit = null;

    }

    private void fillComboSearch() {
        jcmb_search.setModel(new DefaultComboBoxModel(getItemsComboSearch()));
    }

    /**
     * Rergesa los filtros a aparecer en el combo
     * @return Object[] - Lista de filtros dispoibles para la pantalla de productos
     */
    private Object[] getItemsComboSearch() {

        return new Object[]{
                    new Filtro("Nombre", "nombre", String.class),new Filtro("Clave", "clave", String.class)};
    }

    private void doEnableBar() {
        jeditionBar.enableBuscar(false);
        jeditionBar.enableEditar(true);
        //jeditionBar.enableElimnar(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpanel_content = new javax.swing.JPanel();
        jpanel_listdata = new javax.swing.JPanel();
        jpanel_filtro = new javax.swing.JPanel();
        jtxt_value = new javax.swing.JTextField();
        jcmb_search = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jbtn_search = new javax.swing.JButton();
        jrdo_equal = new javax.swing.JRadioButton();
        jrdo_contentwords = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableProducts = new javax.swing.JTable();
        jpanel_editing = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jeditionBar = new org.developercircle.beans.JEditionBar();

        setPreferredSize(new java.awt.Dimension(786, 536));
        setLayout(new java.awt.BorderLayout());

        jpanel_content.setLayout(new java.awt.CardLayout());

        jpanel_listdata.setLayout(new java.awt.BorderLayout());

        jpanel_filtro.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de búsqueda"));

        jLabel2.setText("Por");

        jbtn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sample/imagen/filter.png"))); // NOI18N
        jbtn_search.setIconTextGap(8);
        jbtn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_searchActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrdo_equal);
        jrdo_equal.setText("Igual");

        buttonGroup1.add(jrdo_contentwords);
        jrdo_contentwords.setSelected(true);
        jrdo_contentwords.setText("Que contenga las palabras");

        javax.swing.GroupLayout jpanel_filtroLayout = new javax.swing.GroupLayout(jpanel_filtro);
        jpanel_filtro.setLayout(jpanel_filtroLayout);
        jpanel_filtroLayout.setHorizontalGroup(
            jpanel_filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_filtroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_filtroLayout.createSequentialGroup()
                        .addComponent(jrdo_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrdo_contentwords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtxt_value, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcmb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
        );
        jpanel_filtroLayout.setVerticalGroup(
            jpanel_filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_filtroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmb_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdo_equal)
                    .addComponent(jrdo_contentwords))
                .addContainerGap())
        );

        jpanel_listdata.add(jpanel_filtro, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(jtableProducts);

        jpanel_listdata.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jpanel_content.add(jpanel_listdata, "LISTING");

        jpanel_editing.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del producto"));

        jLabel22.setText("Nombre");

        jLabel23.setText("Clave");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 204, 51));
        jLabel29.setText("*");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 204, 51));
        jLabel32.setText("*");

        javax.swing.GroupLayout jpanel_editingLayout = new javax.swing.GroupLayout(jpanel_editing);
        jpanel_editing.setLayout(jpanel_editingLayout);
        jpanel_editingLayout.setHorizontalGroup(
            jpanel_editingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_editingLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpanel_editingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanel_editingLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel29))
                    .addGroup(jpanel_editingLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_editingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(txtClave))
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jpanel_editingLayout.setVerticalGroup(
            jpanel_editingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_editingLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpanel_editingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel29))
                .addGap(12, 12, 12)
                .addGroup(jpanel_editingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel32))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jpanel_content.add(jpanel_editing, "EDITION");

        add(jpanel_content, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("control"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sample/imagen/help.png"))); // NOI18N
        jLabel1.setText("Visualiza, edita y elimina Tipos de Departamento  del catálogo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName(""); // NOI18N

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel4.add(jeditionBar, java.awt.BorderLayout.EAST);

        add(jPanel4, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_searchActionPerformed

        try {

            List<Departamento> depto = new ArrayList<Departamento>();
            if (!jtxt_value.getText().isEmpty()) {
                Filtro f = (Filtro) jcmb_search.getModel().getSelectedItem();
                if (jrdo_equal.isSelected()) {
                    f.setType(Filtro.EQUAL);
                } else {
                    f.setType(Filtro.LIKE);
                }
                f.setValue(jtxt_value.getText());

                depto = daoDepartamento.listar(f);

            } else {
                depto = daoDepartamento.listar();
            }

            model.clear();
            loadData(depto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error:",JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_jbtn_searchActionPerformed


    private void showOnLayout(String namePanel) {
        currentView = namePanel;
        CardLayout lyt = (CardLayout) jpanel_content.getLayout();
        lyt.show(jpanel_content, namePanel);
    }

    private void createTableDepartamento() {
        RichColumnModel columnModel = new RichColumnModel();

        columnModel.add(new RichDataColumn(String.class, "Clave", "clave", false));
        columnModel.add(new RichDataColumn(String.class, "Nombre", "nombre", false));
        model = new RichTableModel(columnModel);
        jtableProducts.setModel(model);
    }

    public void refreshData() {
        model.clear();
        loadData();
    }

    private void loadData() {
        try {
            List<Departamento> deptos = daoDepartamento.listar();
            loadData(deptos);
        } catch (DataServiceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error:", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadData(List<Departamento> depto) {
        for (Departamento dep : depto) {
            model.addRow(dep);
        }
    }

    /**
     * Metodo que llena con informacion los controles del formulario de Producto
     * @param d un producto
     */
    private void fillControls(Departamento d) {
        txtClave.setText(d.getClave());
        txtNombre.setText(d.getNombre());
    }

    private void fillDepartamento(Departamento d) {
        if (isValidated()) {
            d.setClave(txtClave.getText());
            d.setNombre(txtNombre.getText());
        }
    }

    /**
     * limpia los controles
     */
    private void clearControls() {
        txtClave.setText("");
        txtNombre.setText("");

    }

    private boolean isValidated() {
        boolean band = false;
        if (!txtClave.getText().trim().isEmpty() && !txtNombre.getText().trim().isEmpty()) {
            band = true;
        }
        return band;
    }

    /**
     * Regresa un producto seleccionado de la tabla
     * @return Producto - un producto selecionado en la tabla de productos
     */
    private Departamento detSelectedDepartamento() {
        Departamento c = null;
        int index = jtableProducts.getSelectionModel().getMinSelectionIndex();

        if (jtableProducts.getSelectionModel().isSelectedIndex(index)) {
            c = (Departamento) model.getData().get(index);
        }
        return c;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_search;
    private javax.swing.JComboBox jcmb_search;
    private org.developercircle.beans.JEditionBar jeditionBar;
    private javax.swing.JPanel jpanel_content;
    private javax.swing.JPanel jpanel_editing;
    private javax.swing.JPanel jpanel_filtro;
    private javax.swing.JPanel jpanel_listdata;
    private javax.swing.JRadioButton jrdo_contentwords;
    private javax.swing.JRadioButton jrdo_equal;
    private javax.swing.JTable jtableProducts;
    private javax.swing.JTextField jtxt_value;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public Departamento getCurrentData() {
        Departamento c = null;
        if (currentView.equals(LIST_PANEL)) {
            c = detSelectedDepartamento();
            if (c == null) {
                Toolkit.getDefaultToolkit().beep();
            }
        } else if (currentView.equals(EDIT_PANEL) && departamentoToEdit != null) {
            fillDepartamento(departamentoToEdit);
            return departamentoToEdit;
        } else {
            //devolvemos un producto nuevo
            c = new Departamento();
            fillDepartamento(c);//llenamos un producto con la informacion del fomulario
        }
        return c;
    }

    @Override
    public boolean cancel() {
        refreshData();
        showOnLayout(LIST_PANEL);
        departamentoToEdit = null;
        return true;
    }

    @Override
    public Departamento search() {
        return null;
    }

    @Override
    public boolean newData() {
        isEdit=false;
        showOnLayout(EDIT_PANEL);
        clearControls();
        departamentoToEdit = null;
        return true;
    }

    @Override
    public boolean edit(Departamento data) {
        isEdit=true;
        if (data != null) {
            departamentoToEdit = data;
            showOnLayout(EDIT_PANEL);
            fillControls(data);
            return true;
        } else {
            return false;
        }

    }

    @Override
    public boolean delete(Departamento data) {
        if (data != null) {
            try {
                
                if (JOptionPane.showConfirmDialog(this,
                        "Realmente desea eliminar el departamento","Atención:",JOptionPane.YES_NO_CANCEL_OPTION) 
                        == JOptionPane.YES_OPTION) {
                    daoDepartamento.borrar(data);
                    showOnLayout(LIST_PANEL);
                    refreshData();
                    departamentoToEdit = null;
                    return true;
                } else {
                    return false;
                }
            } catch (DataServiceException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(),"Error:",JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            return false;
        }
    }

    @Override
    public boolean save(Departamento data) {
        //System.out.println(data+"---------------------------------------------------------------"+jtxt_codebar.getText());
        //if (!jtxt_nombre.getText().trim().isEmpty()&&!jtxt_codebar.getText().trim().isEmpty()&&!jtxt_unidad.getText().trim().isEmpty()&&!jtxt_costo.getText().trim().isEmpty()) {
        //if (data !=null) {
        if (isValidated()) {
            try {
                if (isEdit)
                    data = daoDepartamento.modificar(data);
                else
                    data = daoDepartamento.guardar(data);
                
                showOnLayout(LIST_PANEL);
                refreshData();
                departamentoToEdit = null;
                return true;
            } catch (DataServiceException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(),"Error:", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this,"Faltan campos","Atención:", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    @Override
    public void cathException(Exception ex) {
        JOptionPane.showMessageDialog(this,ex.getMessage(),"Error:", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public boolean foundData(Departamento found) {
        return false;
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            //nos permitira observar si se selecciona algun elemento d ela lista
            int i = jtableProducts.getSelectionModel().getMinSelectionIndex();
            if (jtableProducts.getSelectionModel().isSelectedIndex(i)) {
                doEnableBar();
            }
        }
    }
}
